[2025-01-19T20:36:56.423+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.load_md_exchange_rate_d scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:36:56.488+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.load_md_exchange_rate_d scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:36:56.491+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-19T20:37:17.581+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_md_exchange_rate_d> on 2025-01-18 00:00:00+00:00
[2025-01-19T20:37:17.605+0000] {standard_task_runner.py:60} INFO - Started process 172 to run task
[2025-01-19T20:37:17.632+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'load_md_exchange_rate_d', 'scheduled__2025-01-18T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpef38kay0']
[2025-01-19T20:37:17.677+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask load_md_exchange_rate_d
[2025-01-19T20:37:18.054+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.load_md_exchange_rate_d scheduled__2025-01-18T00:00:00+00:00 [running]> on host b8f36627e35c
[2025-01-19T20:37:18.518+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dmitry' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='load_md_exchange_rate_d' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-18T00:00:00+00:00'
[2025-01-19T20:37:18.701+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:19.225+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:19.369+0000] {sql.py:450} INFO - Running statement: 
    SELECT ds.upsert_table('md_exchange_rate_d', 'tmp_md_exchange_rate_d');
    , parameters: None
[2025-01-19T20:37:19.411+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:24.472+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:24.694+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO logs.data_load_log (process_name, start_time, end_time, status, rows_loaded, message)
        VALUES (%s, %s, %s, %s, %s, %s)
        , parameters: ('Load process for md_exchange_rate_d', datetime.datetime(2025, 1, 19, 20, 37, 18, 521933), datetime.datetime(2025, 1, 19, 20, 37, 24, 421581), 'Completed', 460, '460 rows affected.')
[2025-01-19T20:37:24.700+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:24.734+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:24.901+0000] {sql.py:450} INFO - Running statement: DROP TABLE IF EXISTS ds.tmp_md_exchange_rate_d;, parameters: None
[2025-01-19T20:37:24.937+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-19T20:37:25.005+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=load_md_exchange_rate_d, execution_date=20250118T000000, start_date=20250119T203656, end_date=20250119T203725
[2025-01-19T20:37:25.204+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-19T20:37:25.488+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
