[2025-01-19T20:36:52.097+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: insert_data.load_ft_posting_f scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:37:01.666+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: insert_data.load_ft_posting_f scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-01-19T20:37:01.669+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-01-19T20:37:01.757+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_ft_posting_f> on 2025-01-18 00:00:00+00:00
[2025-01-19T20:37:01.839+0000] {standard_task_runner.py:60} INFO - Started process 161 to run task
[2025-01-19T20:37:01.918+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'insert_data', 'load_ft_posting_f', 'scheduled__2025-01-18T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpdl2_wlci']
[2025-01-19T20:37:01.941+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask load_ft_posting_f
[2025-01-19T20:37:03.908+0000] {task_command.py:423} INFO - Running <TaskInstance: insert_data.load_ft_posting_f scheduled__2025-01-18T00:00:00+00:00 [running]> on host b8f36627e35c
[2025-01-19T20:37:04.221+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='dmitry' AIRFLOW_CTX_DAG_ID='insert_data' AIRFLOW_CTX_TASK_ID='load_ft_posting_f' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-18T00:00:00+00:00'
[2025-01-19T20:37:04.437+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:10.380+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:10.778+0000] {sql.py:450} INFO - Running statement: 
    SELECT ds.upsert_table('ft_posting_f', 'tmp_ft_posting_f');
    , parameters: None
[2025-01-19T20:37:11.164+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:16.229+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:16.403+0000] {sql.py:450} INFO - Running statement: 
        INSERT INTO logs.data_load_log (process_name, start_time, end_time, status, rows_loaded, message)
        VALUES (%s, %s, %s, %s, %s, %s)
        , parameters: ('Load process for ft_posting_f', datetime.datetime(2025, 1, 19, 20, 37, 4, 226311), datetime.datetime(2025, 1, 19, 20, 37, 16, 215855), 'Completed', 33892, '33892 rows affected.')
[2025-01-19T20:37:16.417+0000] {sql.py:459} INFO - Rows affected: 1
[2025-01-19T20:37:16.459+0000] {base.py:83} INFO - Using connection ID 'postgres-db' for task execution.
[2025-01-19T20:37:16.562+0000] {sql.py:450} INFO - Running statement: DROP TABLE IF EXISTS ds.tmp_ft_posting_f;, parameters: None
[2025-01-19T20:37:16.595+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-01-19T20:37:16.658+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=insert_data, task_id=load_ft_posting_f, execution_date=20250118T000000, start_date=20250119T203652, end_date=20250119T203716
[2025-01-19T20:37:16.829+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-01-19T20:37:16.899+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
